### ISSUE TITLE
[2.0.3-beta] Cannot read property 'isLive' of undefined

### ISSUE THREAD

**Issue by me-vlad** [clappr/dash-shaka-playback#12]
Browser: All with MSE? (tested on Chrome, Chromium)

Clappr Version: 0.2.49
dash-shaka-playback version: 2.0.3-beta

Steps to reproduce:

- open http://cdn.clappr.io/ and change source to http://demo.unified-streaming.com/video/ateam/ateam.ism/ateam.mpd
- enable dash-shaka-playback Plugin https://cdn.jsdelivr.net/clappr.dash-shaka-playback/latest/dash-shaka-playback.js
- click on Run button,
you'll see an error message: Cannot read property 'isLive' of undefined
- click on Play button - default mp4 source (http://clappr.io/highline.mp4) playing instead of mpeg-dash stream

config tested with cdn.clappr.io:

var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://demo.unified-streaming.com/video/ateam/ateam.ism/ateam.mpd',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [DashShakaPlayback]
});

player.attachTo(playerElement);

![2016-05-07 14-40-07](https://cloud.githubusercontent.com/assets/222185/15091918/f2a055e6-1461-11e6-8af9-61839b63b194.png)

**Comment by leandromoreira** [comment]
thanks :)
