### ISSUE TITLE
[stable 1.0.12] Cannot set property 'shaka' of undefined 

### ISSUE THREAD

**Issue by me-vlad** [clappr/dash-shaka-playback#15]
Browser: All with MSE (tested on Chrome, Chromium)

Clappr Version: 0.2.57
dash-shaka-playback version: 1.0.12

Steps to reproduce:

- open http://cdn.clappr.io/ and change source to http://demo.unified-streaming.com/video/ateam/ateam.ism/ateam.mpd
- enable dash-shaka-playback Plugin (1.0.12) https://cdn.jsdelivr.net/clappr.dash-shaka-playback/1.0.12/dash-shaka-playback.js
- click on Run button, you'll see an error message: Cannot set property 'shaka' of undefined 
- click on Play button - default mp4 source (http://clappr.io/highline.mp4) playing instead of mpeg-dash stream

config tested with cdn.clappr.io:

``` javascript
var playerElement = document.getElementById("player-wrapper");
Clappr.Log.setLevel(0);
var player = new Clappr.Player({
  source: 'http://demo.unified-streaming.com/video/ateam/ateam.ism/ateam.mpd',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [DashShakaPlayback]
});
player.attachTo(playerElement);
```

![2016-06-27 22-22-57](https://cloud.githubusercontent.com/assets/222185/16392716/f6032714-3cb5-11e6-84d3-4c26077a3f29.png)

**Comment by leandromoreira** [comment]
Thanks @me-vlad ! is this reproducible on BETA version? can you use the "BETA"?

**Comment by me-vlad** [comment]
@leandromoreira  my DASH stream has some issues with shaka2, so currently I use shaka1 (dash-shaka-playback stable with older clappr 0.2.51)

**Comment by leandromoreira** [comment]
@me-vlad okay, I'll branch out then and try to fix! :) if you want, you can open issues to theses issues too.

**Comment by me-vlad** [comment]
@leandromoreira thanks! 
I think shaka2 issue not caused by clappr plugin, I can reproduce it on shaka demo page http://shaka-player-demo.appspot.com/demo/

**Comment by leandromoreira** [comment]
You can then open an issue at https://github.com/google/shaka-player to help them build a better player!

**Comment by me-vlad** [comment]
@leandromoreira sure, I'll clarify details and will open an issue at shaka-player repo

**Comment by leandromoreira** [comment]
you can refer this issue there too if you want.

**Comment by leandromoreira** [comment]
@me-vlad https://github.com/clappr/dash-shaka-playback/releases/tag/1.0.13 can you test it?

**Comment by me-vlad** [comment]
@leandromoreira  just tested on [cdn.clappr.io](http://cdn.clappr.io) with v. 1.0.13 from https://cdn.jsdelivr.net/clappr.dash-shaka-playback/1.0.13/dash-shaka-playback.js 

I see an error after clicking on Run button:
Cannot read property 'isLive' of undefined



![2016-06-28 19-01-56](https://cloud.githubusercontent.com/assets/222185/16422999/033e7b9c-3d63-11e6-9fde-70af8d3ebaed.png)

**Comment by leandromoreira** [comment]
it should be fixed now @me-vlad thanks again

**Comment by me-vlad** [comment]
@leandromoreira  sorry but with  version 1.0.14 from https://cdn.jsdelivr.net/clappr.dash-shaka-playback/1.0.14/dash-shaka-playback.js  - same error on [cdn.clappr.io](http://cdn.clappr.io/)

**Comment by leandromoreira** [comment]
I see, the weird thing is if you just use the playback (npm start) everything run just fine.

**Comment by leandromoreira** [comment]
hopefully https://github.com/clappr/dash-shaka-playback/releases/tag/1.0.16 will solve

**Comment by me-vlad** [comment]
@leandromoreira  cool, it works!
just one minor issue - stream starts just after second click on the player

**Comment by leandromoreira** [comment]
I'm trying to fix that now @me-vlad :D 17 is up!

**Comment by leandromoreira** [comment]
17 does not solve that too!

**Comment by leandromoreira** [comment]
I bet 18 solves it.

**Comment by me-vlad** [comment]
:) yes, but... 
after clicking on stop button player starts buffering

**Comment by leandromoreira** [comment]
is it live? do you have this source?

**Comment by me-vlad** [comment]
yes, you can try with this stream 
http://live.unified-streaming.com/loop/loop.isml/loop.mpd

``` javascript
var playerElement = document.getElementById("player-wrapper");
Clappr.Log.setLevel(0);
var player = new Clappr.Player({
  source: 'http://live.unified-streaming.com/loop/loop.isml/loop.mpd',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [DashShakaPlayback]
});
player.attachTo(playerElement);
```

**Comment by leandromoreira** [comment]
@me-vlad I think it's finally solved thank you so much for all the tests, can you redo all of them?

**Comment by me-vlad** [comment]
@leandromoreira  thanks, I tested live and vod stream again with https://cdn.jsdelivr.net/clappr.dash-shaka-playback/1.0.19/dash-shaka-playback.js, VOD works fine.
Live stream starts, after clicking on stop button stream stops and mediacontrol bar disappears but big play button not appears.
Streams starts again after click on the player.

Live test config:

``` javascript
var playerElement = document.getElementById("player-wrapper");
Clappr.Log.setLevel(0);
var player = new Clappr.Player({
  source: 'http://live.unified-streaming.com/loop/loop.isml/loop.mpd',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [DashShakaPlayback],
  hideMediaControl: false
});
player.attachTo(playerElement);
```

**Comment by leandromoreira** [comment]
@me-vlad I'm going to close this one and I ask you to open a new one :) (I noticed someone had catch this same bug while on hls ... maybe this is a clappr related, anyway)

**Comment by leandromoreira** [comment]
@me-vlad lol https://github.com/clappr/clappr/issues/1062 I fixed

**Comment by leandromoreira** [comment]
let's wait a new clappr then we can update both versions! Thanks again.
