### ISSUE TITLE
Audio tracks

### ISSUE THREAD

**Issue by halibegic** [clappr/dash-shaka-playback#16]
How to call [audio API](https://github.com/clappr/dash-shaka-playback#extra-features) in order to list / set audio tracks. Example: https://jsfiddle.net/halibegic/ohovkrbv/

P.S stream "angel-one" contains the following tracks:
- language: de, 131357 bits/s
- language: en, 130201 bits/s
- language: es, 132963 bits/s
- language: fr, 134350 bits/s
- language: it, 134045 bits/s

**Comment by leandromoreira** [comment]
@halibegic this should work https://jsfiddle.net/ohovkrbv/2/ but it's not I'm looking into to understand (but at least you can see how it can be done)

**Comment by leandromoreira** [comment]
@halibegic it works :P you just need to:

First gather the tracks:

```javascript
player.on(Clappr.Events.PLAYER_PLAY, function(){
  var clapprShaka = player.core.getCurrentContainer().playback
  var options = clapprShaka.audioTracks;
  console.log(options);
})
```

And then create an UI (binding onClick) to change it:

```
clapprShaka.selectTrack(options[0]);
```

**Comment by halibegic** [comment]
I will try :) Thank You

**Comment by halibegic** [comment]
I don't know why but first time playing I need to click two times in order to change audio https://jsfiddle.net/halibegic/ohovkrbv/12/

**Comment by leandromoreira** [comment]
I'll check it, I also would point you to this project https://github.com/clappr/clappr-level-selector-plugin it might inspire you.

**Comment by leandromoreira** [comment]
@halibegic can you test with the newer version?
