### ISSUE TITLE
Feature request : add "external" shaka plugin version in compilation

### ISSUE THREAD

**Issue by kslimani** [clappr/dash-shaka-playback#28]
I created an issue to continue discution started in https://github.com/clappr/dash-shaka-playback/pull/22#issuecomment-315020126.

(will also create a PR proposal).

Goal is to modify plugin compilation to add an additional version of the plugin without shaka-player bundled.

My current proposition is : 

* to keep the current filename `dash-shaka-playback.js` for the version with shaka-player bundled.
* to add a new `dash-shaka-playback-external.js` file for version without shaka-player bundled.

Note: `dash-shaka-playback-external.js` name is only a proposition, i guess someone may have a better idea 😄 

/poke @tchakabam  @leandromoreira @vagnervjs @towerz

**Comment by leandromoreira** [comment]
I really liked your current proposition. 👍  Thank you @kslimani

**Comment by kslimani** [comment]
@leandromoreira i see also that in current master, a compilation "behaviour" has been broken since 2.0.7 release tag : 

Previously, `npm run build` was compiling **unminified** es5 "dist" version and `npm run release` was compiling the **minified** es5 "dist" version. Do you want me to restore this in my (_incoming soon_) PR ?
(_i ask because the bump shell script is expecting this behaviour_).

I propose also to add an `npm run dist` shortcut which will run the `build` and `release` npm tasks.

**Comment by leandromoreira** [comment]
>  Do you want me to restore this in my (incoming soon) PR ?

No, I think this is better.

**Comment by kslimani** [comment]
@leandromoreira  then you should revert, because in my PR i restore the previous behaviour

**Comment by leandromoreira** [comment]
I loved the `npm run dist` that does all. Is it now releasing a minified es6?

**Comment by kslimani** [comment]
In the current merged PR : 

* `npm run build` create the **unminified** es5 plugin bundle file
* `npm run release` create the two **minified** es5 plugin bundle files (_with and without shaka as external lib_)
* `npm run dist` ==>  `npm run lint && npm run build && npm run release`

**Comment by kslimani** [comment]
So, if you run `npm run dist`, it will run lint task and then generate the following files :

```
// The es5 plugin unminified with shaka-player bundled
dash-shaka-playback.js
dash-shaka-playback.js.map

// The es5 plugin minified with shaka-player bundled
dash-shaka-playback.min.js
dash-shaka-playback.min.js.map

// The es5 plugin minified without shaka-player bundled
dash-shaka-playback-external.min.js
dash-shaka-playback-external.min.js.map
```

**Comment by leandromoreira** [comment]
I think this solution you did is perfect!

**Comment by kslimani** [comment]
Ok, then, no revert is required 👍 

Please note, that you will need to run yourself (_or another core member_) the `dist` task and commit to master in order to create the new bundle files.

**Comment by kslimani** [comment]
@tchakabam could you please get current master and verify if it satisfy your needs ?

**Comment by leandromoreira** [comment]
Ohh yeah, I'm planning to do a new release, @kslimani did you tried with newer clappr? can I `npm publish` it too? 

If the answer is yes for all questions above I'll be happy to release a new version, are you girls/guys @tchakabam @vagnervjs @towerz okay with that?

**Comment by vagnervjs** [comment]
That's fine by me, great work again @kslimani!

**Comment by kslimani** [comment]
I have not made intensive tests, i just checked that webpack-dev-server demo page run with `npm start` was working. I was relaying on @tchakabam to performs additional tests. (_especially the "shaka less" bundle_)

BTW @leandromoreira i am also planning to add new Clappr closed caption capability support to this plugin. (_but no eta, maybe next week, it is Bastille Day tomorrow in France_). I will build a custom Clappr player from master to tests as it is not released yet.

**Comment by leandromoreira** [comment]
😄  don't worry enjoy your Bastille Day there.

**Comment by tchakabam** [comment]
@kslimani Hey thanks for the notice! I'll get back to you with the test results on monday, but code-wise it looks all great! :)

**Comment by tchakabam** [comment]
@kslimani hey but what is now with an external bundle that is not minified :dagger: 

seems we dont have that anymore now :(

**Comment by tchakabam** [comment]
i ll make a PR for that ;) otherwise looks fine to me.

**Comment by tchakabam** [comment]
https://github.com/clappr/dash-shaka-playback/pull/33

**Comment by leandromoreira** [comment]
It's done! 💃  thanks a lot, @kslimani  and @tchakabam
