### ISSUE TITLE
JFYI: Shaka 2 coming soon

### ISSUE THREAD

**Issue by joeyparrish** [clappr/dash-shaka-playback#4]
JFYI, Shaka team is hard at work on Shaka 2, which will have a new API.  You can see a preview of the work-in-progress on the [preview branch](https://github.com/google/shaka-player/tree/preview/).  We also published a [redesign doc](https://github.com/google/shaka-player/blob/preview/docs/design/REDESIGN.md) with a roughed-out version of the new APIs and diagrams of the new architecture.

I'll update this ticket once we go into beta so that you have a chance to give feedback on the API and start working on updates to your clappr plugin to support Shaka 2.  We expect the official release of Shaka 2.0.0 by end of March.  Thanks!

**Comment by leandromoreira** [comment]
Congrats @joeyparrish and the team,  I'm looking forward for this, thanks for all the work! :beers:

**Comment by leandromoreira** [comment]
Fixed links: [redesign](https://github.com/google/shaka-player/blob/master/docs/design/REDESIGN.md) and it already points to master :grinning:

**Comment by joeyparrish** [comment]
Yes indeed!  We recently merged to master and hope to release beta soon.

**Comment by joeyparrish** [comment]
We've just released [v2.0.0-beta](https://github.com/google/shaka-player/tree/v2.0.0-beta) on github & npm.  Let us know what you think.

We're still working on the v2 upgrade guide, but we have [tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) on several other topics already.  Hopefully that will be enough to get you started, and you can always reach out via email or github if there's anything we can do to help with the transition.

Thanks!

**Comment by leandromoreira** [comment]
Thanks @joeyparrish and all the team, soon I'll be trying it.

**Comment by leandromoreira** [comment]
It's looking pretty cool, although I just read the first [two](http://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) pages from the tutorial. But it was enough [to make it work](https://github.com/clappr/dash-shaka-playback/tree/shaka.2.0.0-beta). 

The only thing I think we'll need to overcome is that, now the checking if the Browser/Device is able to play become an async method [Player.support](http://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#support) which returns a Promise.

On Clappr we have a sync static method [canPlay](http://clappr.github.io/classes/Playback.html#method_canPlay) that all the playback must implement, therefore we'll need to think about solutions for this. 

Anyway, I think the full integration will be seamless, thanks once again. I'll try to dig deeper in the design and general changes. (looking forward to test a replace plugin for network request using WebRTC to offer P2P)

**Comment by leandromoreira** [comment]
I'm noticing a lot less "rebuffering" maybe it's because now the example stream is hosted in a better place http://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**Comment by leandromoreira** [comment]
I ran a basic profile (on chrome) oriented to CPU and HEAP-wise and notice that both versions are almost the same (shaka 2.0.0-beta vs shaka 1.6.4):

![alt CPU](http://s22.postimg.org/v5v4c8hmp/Screen_Shot_2016_04_08_at_12_07_22_AM.png)
![alt HEAP](http://s22.postimg.org/n1rll8kld/Screen_Shot_2016_04_08_at_12_08_31_AM.png)

**Comment by joeyparrish** [comment]
We have always tried to avoid doing anything CPU-heavy in Shaka, and we took extra care with `destroy()` in v2 to clean up after ourselves, so I'm glad to hear that it profiles well for you.

Regarding Player.support being async, unfortunately, this is the only way we can return a map of supported key systems.  The EME API is Promise-based.  Is key system information useful to you?

**Comment by leandromoreira** [comment]
>  Is key system information useful to you?

Yeah, there was one guy that [opened an issue](https://github.com/clappr/dash-shaka-playback/issues/5) for that and I think it's very useful.

I was thinking about offering a [sync basic implementation](https://github.com/google/shaka-player/blob/master/lib/player.js#L233-L238) (which will work for most cases) and postpone the final decision based on `Player.support`

**Comment by leandromoreira** [comment]
Yet on the feedbacks, the code is easier to read and extend :)

**Comment by joeyparrish** [comment]
Glad to hear it!

**Comment by leandromoreira** [comment]
- [ ] add support to `canPlay` asynchronously

* one way to implement the async `canPlay` is to signalize the lack of support to a static method (`DashShakaPlayback.supportedStatus`) then check that on the player. But that might force a polling or on check onError

**Comment by leandromoreira** [comment]
New configuration with that many options to fine tune is pretty cool!

**Comment by leandromoreira** [comment]
@joeyparrish I'm listening to `player.addEventListener('buffering', this._bufferingHandler.bind(this))` and the parameter received has not `buffering` property but the [doc](http://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#event:BufferingEvent), what's the way to check weather is the start or the end?

**Comment by leandromoreira** [comment]
Despite the `canPlay` and adaptation/buffering event I release a beta version too.

**Comment by joeyparrish** [comment]
With regard to buffering events, there should definitely be a `buffering` property:

```js
shaka.Player.prototype.onBuffering_ = function(buffering) {
  // Before setting |buffering_|, update the time spent in the previous state.
  this.updateStats_();
  this.buffering_ = buffering;

  var event = new shaka.util.FakeEvent('buffering', { buffering: buffering });
  this.dispatchEvent(event);
};
```

`AdaptationEvent` in v2 does not contain details about the adaptation decision, which may have applied to multiple tracks.  You can call `player.getTracks()` and see which tracks have `active: true` when you receive the event.

Does this help?

**Comment by leandromoreira** [comment]
Thanks @joeyparrish , it does helps!

About the 'buffering' event, what I did was to add a listener for 'buffering' `player.addEventListener('buffering', (e) => console.log(e))`, I noticed that it fires twice but none with buffering property.

![error screenshot](http://s32.postimg.org/ufyjefihx/Screen_Shot_2016_05_02_at_8_32_31_AM.png "error screenshot")

**Comment by joeyparrish** [comment]
Ah, it looks like a renaming bug in the compiled version.  The property has been renamed, but it shouldn't have been.  I filed https://github.com/google/shaka-player/issues/361 to track.

**Comment by leandromoreira** [comment]
I see, I bet is that `a` value.

**Comment by joeyparrish** [comment]
We will have another beta release (v2.0.0-beta2) this week if possible.  I will try to have the event properties (google/shaka-player#361) fixed in that release.

Regarding adaptation, from your link it seems that you already have a solution.  Or perhaps I don't fully understand the problem.  Can you clarify, please?  Do you need track information in the `AdaptationEvent`?  Or is it inconvenient that `getTracks()` returns all three types?

**Comment by leandromoreira** [comment]
> Regarding adaptation, from your link it seems that you already have a solution. Or perhaps I don't fully understand the problem. Can you clarify, please? Do you need track information in the AdaptationEvent? Or is it inconvenient that getTracks() returns all three types?

Yes, it's a solved problem, I'm just sharing what I did, I personally think it's best to offer a generic and extensible component.

**Comment by leandromoreira** [comment]
@joeyparrish yet on the adaptation event, it seems that when you call `selectTrack` passing the track (not only the id but the object) it doesn't fire 'adaptation' again:
```javascript
    // turn on or off (depends on the user selection)
    this._player.configure({abr: {enable: !isAuto}})
    this._player.selectTrack(track)
```

I logged the events and I got:

- adaptation id 10
- adaptation id 13
- selectTrack id 9

But there is no `adaptation id 9` as reaction to `this._player.selectTrack(track)`

**Comment by joeyparrish** [comment]
That's correct.  AdaptationEvents are for changes made by the AbrManager.  When you call `selectTrack`, presumably, you know you've called it.  Also note that `selectTrack()` for audio and video tracks disables ABR.

**Comment by leandromoreira** [comment]
> you know you've called it.

is this sync? I mean, right after I call `selectTrack` the track was already changed?

**Comment by leandromoreira** [comment]
@joeyparrish do you have a slacker channel or other way (irc...) to communicate?

**Comment by joeyparrish** [comment]
Yes, it's synchronous, with the understanding that the StreamingEngine may not request a new segment right away.  But the next time it does, it's from the new track.

Sorry, I'm not available for live chat at the moment.  We don't have an IRC or slacker channel for the team, either.  If email works for you, you can find my email address in CONTRIBUTORS.

**Comment by leandromoreira** [comment]
Thanks , then I'll use it as sync method.

I'm having some ideas (mostly about extensibility) but maybe the better place to discuss them it's here.

**Comment by joeyparrish** [comment]
Yes, please give us feedback on the API while we are still in beta and can make API changes more easily.  The best place for feedback is either the mailing list or github issues.  Thanks!

**Comment by leandromoreira** [comment]
I tried to access these "methods" and they weren't there, are they private?
```javascript
    var manifest = shaka.media.ManifestParser.support();
    var media = shaka.media.MediaSourceEngine.support();
```

**Comment by leandromoreira** [comment]
What is the best method to access weather the player is with ABR on or off?

**Comment by joeyparrish** [comment]
Those methods are not exported from the library.  They are "public" within the library (class-to-class), but "private" with respect to the application.

**Comment by leandromoreira** [comment]
The new version fixed the buffering issue (among tons of other), thanks!

**Comment by joeyparrish** [comment]
@leandromoreira, we've just released [v2.0.0-beta3](https://github.com/google/shaka-player/tree/v2.0.0-beta3) on github & npm.  The upgrade guide is available [here](http://shaka-player-demo.appspot.com/docs/api/tutorial-upgrade.html).  Let us know what you think!

**Comment by leandromoreira** [comment]
@joeyparrish thanks :) I'll take a look later!

**Comment by leandromoreira** [comment]
@joeyparrish [with minimal effort](https://github.com/clappr/dash-shaka-playback/commit/5cb7c73a3fe284e67da1d758f75d8173bb9feed3), everything is working just fine! Kudos again to everyone!

> Pretty neat the new content protection configuration.

```javascript
```

**Comment by joeyparrish** [comment]
Cool, thanks for the feedback!

**Comment by leandromoreira** [comment]
@joeyparrish are any plans to add support to Adobe Access?

**Comment by joeyparrish** [comment]
We don't *not* support Adobe Access.  We support EME, so as long as Adobe Access is interoperable with other EME key systems, I see no reason it shouldn't just work.  That said, we currently have no public DASH test vectors using Adobe Access, so we can't confirm.

**Comment by leandromoreira** [comment]
Thanks @joeyparrish I got it.

**Comment by joeyparrish** [comment]
Just wanted to let you know that v2.0.0 is officially out of beta.  Thanks again for your involvement and feedback!

**Comment by leandromoreira** [comment]
@joeyparrish you're welcome, btw we (the company I'm currently working) are planing to use with Shaka 👍  (actually we use clappr therefore we'll use this wrapper (dash-shaka-playback) but for sure Shaka is the ⭐  while playing dash)

**Comment by joeyparrish** [comment]
Nice!
