### ISSUE TITLE
DRM License URL

### ISSUE THREAD

**Issue by abdul** [clappr/dash-shaka-playback#5]
A lot of people use Shaka Player for it's capabilities to play DRM (widevine and playready) protected content. 

Can you please add a way to let people specify license-urls?  

The easiest way I think of:

`this._player.load(new shaka.player.DashVideoSource(this.options.src, interpretContentProtection))`

```
 /**
     * @param {string} schemeIdUri The ContentProtection's scheme ID URI.
     * @param {!Element} contentProtection The ContentProtection element.
     * @return {!Array.<shaka.player.DrmInfo.Config>} An array of Config
     *     objects or null if the element is not understood by this application.
     */
     function interpretContentProtection (schemeIdUri, contentProtection) {

      }
```
Let people override interpretContentProtection?

Thank you
-abdul

**Comment by leandromoreira** [comment]
Thanks for the heads up @abdul I'll check that later :smile:

**Comment by leandromoreira** [comment]
@abdul can you test it now?

**Comment by abdul** [comment]
@leandromoreira it works, thank you :-)
