### ISSUE TITLE
Shaka fails to play when Clappr.autoplay is false

### ISSUE THREAD

**Issue by Netherdrake** [clappr/dash-shaka-playback#51]
I'm running into a peculiar issue with Clappr + DASH.

When Clappr.autoplay is true, the video plays fine and everything works as expected. However, if I set the `autoplay` to false, the video won't load and all I get is this error:
<img width="379" alt="screen shot 2018-05-13 at 11 31 26 am" src="https://user-images.githubusercontent.com/3516903/39965864-9c6ae374-56a1-11e8-93f1-68039f77b4f8.png">

No warnings in console.

Dependencies:
```
    "clappr": "^0.2.86",
    "dash-shaka-playback": "^2.2.1",
```

Initialization code:
```js
        player = new Clappr.Player({
            sources: sources,
            poster: `${cdnUrl}/${manifest.cover}`,
            mute: false,
            height: window.innerHeight - 1,
            width: '100%',
            autoPlay: {{ autoPlay | int }},
            scrubThumbnails: {
                backdropHeight: 0,  // 100 gives a nice effect
                spotlightHeight: 135,  // original is 135
                thumbs: thumbnailsSprite(manifest)
            },
            plugins: [
                DashShakaPlayback,
                ClapprThumbnailsPlugin,
                PlaybackSpeedPlugin
            ]
        });
        player.attachTo(document.getElementById("player-full"));
```

Sources:
```js
let sources = ["http://cdn-dev.view.ly/v1/jpYtZ8IgEiSb/mpeg-dash/main.mpd", "http://cdn-dev.view.ly/v1/jpYtZ8IgEiSb/fallback/720p.mp4"]
```

HTML:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Embedded Player</title>
    <style>body {margin:0}</style>
    {% include 'partials/player_js.html' %}
</head>
<body>

<span id="player-full"
      style="border: 0px;border-radius: 0px;width: 100%;height: 100%"></span>

</body>
</html>
```

EDIT:
This issue is present in both Chrome or Firefox.

**Comment by kslimani** [comment]
@Netherdrake is your browser Chrome version 66 ?
If yes, it *may* be related to [this issue](https://github.com/clappr/clappr/issues/1639) _(to confirm)_
Does autoplay fails also on Firefox 60 ?

**Comment by kslimani** [comment]
For an unknown reason, it seems with autoPlay false that video element *may* trigger an error. (which cause the default error page to be displayed).

A workaround is to add the following line at the beginning of  [_onError()](https://github.com/clappr/dash-shaka-playback/blob/master/src/clappr-dash-shaka-playback.js#L312) method :

```javascript
    if (! this._player)  return
```

**Comment by kslimani** [comment]
For completeness here the [commit](https://github.com/clappr/clappr/commit/5dcb887431d7bc347842143104756e53cc1ccef9#diff-2c2c8cae7099c541811236d5f7c5d53d) renaming the method.

In fact, i think that this error has always been there since start but not noticed until error page refactor in Clappr.
