### ISSUE TITLE
Shaka namespace needed

### ISSUE THREAD

**Issue by mrlika** [clappr/dash-shaka-playback#53]
To integrate [P2P Media Loader](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-shaka) engine with Shaka Player in Clappr we need both: shaka player instance and shaka namespace object. Namespace object is not available.

```ts
function registerParserProxies() {
    debug("register parser proxies");
    shaka.media.ManifestParser.registerParserByExtension("mpd", ShakaDashManifestParserProxy);
    shaka.media.ManifestParser.registerParserByMime("application/dash+xml", ShakaDashManifestParserProxy);
    shaka.media.ManifestParser.registerParserByExtension("m3u8", ShakaHlsManifestParserProxy);
    shaka.media.ManifestParser.registerParserByMime("application/x-mpegurl", ShakaHlsManifestParserProxy);
    shaka.media.ManifestParser.registerParserByMime("application/vnd.apple.mpegurl", ShakaHlsManifestParserProxy);
}

function initializeNetworkingEngine() {
    debug("init networking engine");
    shaka.net.NetworkingEngine.registerScheme("http", processNetworkRequest);
    shaka.net.NetworkingEngine.registerScheme("https", processNetworkRequest);
}
```

See details:
https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-shaka/lib/integration.ts

Can you make somehow the namespace available to hook into shaka.net and shaka.media before Shaka Player object creation? For example:

```js
var shakaNamespace = DashShakaPlayback.getShakaNamespace();
```

**Comment by kslimani** [comment]
Maybe simply add a getter, like we did for [HLSJS playback](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L106),  for example :

```javascript
  static get SHAKA() {
    return shaka
  }
```

And the player instance should be available with the [shakaPlayerInstance](https://github.com/clappr/dash-shaka-playback/blob/master/src/clappr-dash-shaka-playback.js#L29) getter. (if created)

**Comment by leandromoreira** [comment]
Thanks you two =) I'll bring @towerz and @vagnervjs I think @kslimani idea's seems pretty solid.

**Comment by greenya** [comment]
Hello guys.
We (me and @mrlika) managed to make all work without this change. We have used "external" version of your library (which comes without bundled ShakaPlayer and relies on global "shaka" included before the library). This way our library and your one uses same "shaka".
