### ISSUE TITLE
Typo variable make level selector pulsing forever

### ISSUE THREAD

**Issue by nemesisqp** [clappr/dash-shaka-playback#56]
```_pendingAdaptationEvent_``` should be ```_pendingAdaptationEvent```
https://github.com/clappr/dash-shaka-playback/blob/a3f96f93e7951ffe5d51eafdb8b4d32f698d9b7c/src/clappr-dash-shaka-playback.js#L342

**Comment by leandromoreira** [comment]
thanks @nemesisqp good catch!
