### ISSUE TITLE
SMPTE-TT bitmap based Subtitle Support

### ISSUE THREAD

**Issue by kumarashu123** [clappr/dash-shaka-playback#59]
shaka-player "version": "2.5.0-beta3" has fixed the issue. In dash-shaka-playback it shows shaka-player version 2.4.4. I tried some approach but it could not helped to update nested dependencies.
Can you please upgrade if it possible or suggest the alternatives.

Kindly refer the link
https://github.com/google/shaka-player/pull/1859 
Thanks in advance

**Comment by leandromoreira** [comment]
@towerz @joaopaulovieira @jhonatangomes are all in favor of updating for `2.5.0-beta3`?

**Comment by leandromoreira** [comment]
and there is also this PR  https://github.com/clappr/dash-shaka-playback/pull/58 that will be added.

**Comment by kumarashu123** [comment]
Hi all, Can you please let me know when 2.5.0-beta-3 will get merged? 
If it takes time Could you please let me know how i can override shaka-players dependency?
My main **challenge** is My application => dash-shaka-playback => shaka-player(need to update this version). 
Please let me know any alternatives to update shaka-players dependency

**Comment by kslimani** [comment]
@kumarashu123 this plugin has a [build version](https://github.com/clappr/dash-shaka-playback/tree/master/dist) without shaka player bundled.

Try to load first your custom shaka player version, then load `dash-shaka-playback.external.min.js` script.

**Comment by kumarashu123** [comment]
shaka-player now we have stable version 2.5.0 [https://github.com/google/shaka-player/releases/tag/v2.5.0](url). Can you please update in dash-shaka-playback.

**Comment by leandromoreira** [comment]
sure thing @kumarashu123 thank you :)
