### ISSUE TITLE
The volume cannot drag

### ISSUE THREAD

**Issue by khanghuynh92** [clappr/dash-shaka-playback#6]
Hi author,

Please help check the volume cannot drag when using dash plugin with clappr lastest version

**Comment by leandromoreira** [comment]
it seems that @jsdelivery changed and the latest version of clappr is not the latest, are you using the cdn version?

**Comment by leandromoreira** [comment]
anyway, I'm debugging to try to figure it out. :) thanks a lot @khanghuynh92

**Comment by leandromoreira** [comment]
@khanghuynh92 please let me know if it was really fixed (I tested locally and it worked)

**Comment by khanghuynh92** [comment]
@leandromoreira I've checked with new build of dash-shaka-playback.js but it's still not drag volume, I'm using lastest version of clappr.min.js thought cdn

**Comment by leandromoreira** [comment]
@khanghuynh92 couldn't you get the latest version? I published on npm.
