### ISSUE TITLE
Error: dash_shaka_playback_1_1002

### ISSUE THREAD

**Issue by hijuuijj** [clappr/dash-shaka-playback#72]
http://rtve-24h-vod-dash.secure.footprint.net/live/nas_live/24h/dash/24h.mpd?begin=&end=&nvb=1527155886&nva=1958691886&hash=009e4d1c3ce13217b621a5f14312e1d0a00e7d2ff

I get this error code many times during the playback: dash_shaka_playback_1_1002
Refreshing the page the stream continues, but after a few seconds the error message reappears.
However VLC works without any problem.

Is there any way to fix it?

Thank you in advance.

**Comment by hijuuijj** [comment]
While there is no solution, is there any way to change the error to auto-refresh? (auto-retry until it works)

**Comment by leandromoreira** [comment]
@hijuuijj I think you can do that https://github.com/clappr/clappr/blob/dev/doc/PLAYER_ERRORS.md#player-errors

**Comment by hijuuijj** [comment]
I can't get it to work... can somebody help me? I just need you to do unlimited retries and show the last frame while is trying to load.

**Comment by leandromoreira** [comment]
The link I posted has a retry example: https://github.com/clappr/clappr/blob/dev/doc/PLAYER_ERRORS.md#example

<img width="719" alt="image" src="https://user-images.githubusercontent.com/55913/72855839-9f62c500-3c97-11ea-8c12-b9a8f18cf389.png">

**Comment by jhonatangomes** [comment]
If you want to use the shaka player options, you can do so by setting the `shakaConfiguration` object into clappr options.

Example:


```js
var player = new Clappr.Player({
  ...
  shakaConfiguration: {
    manifest: {
      retryParameters: {
        maxAttempts: Infinity,
      }
    },
    streaming: {
      retryParameters: {
        maxAttempts: Infinity,
      }
    },
    ...
  }
  ...
})
```

Keep in mind that by setting the `maxAttempts` to Infinity will never trigger a streaming/manifest error.

**Comment by jhonatangomes** [comment]
I'd also recommend you to check why the error 1002 is happening.

You can get information about this error [here](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html) and [here](https://github.com/google/shaka-player/blob/master/docs/tutorials/faq.md)

**Comment by hijuuijj** [comment]
Please could you edit and complete your code with my URL? I get a black screen.
Thank you for your help.
